# Generated by Django 5.2.11 on 2026-02-28 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_id', models.CharField(blank=True, help_text='Identifier from the browser extension', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('ai_detected', models.BooleanField(default=False)),
                ('fake_news_detected', models.BooleanField(default=False)),
                ('harmful_content_detected', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_sites', to='portal.child')),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
