# Generated by Django 5.2.11 on 2026-02-28 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_replace_child_with_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='portal.device')),
            ],
            options={
                'ordering': ['value'],
                'unique_together': {('device', 'value')},
            },
        ),
        migrations.CreateModel(
            name='DeviceWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_entries', to='portal.device')),
            ],
            options={
                'ordering': ['value'],
                'unique_together': {('device', 'value')},
            },
        ),
    ]
