/**
 * Extension config for AWS deployment (generated by scripts/aws_deploy.py).
 * Use this file when packaging the extension for production (or copy PORTAL_API_BASE / GATEWAY_BASE_URL into config.js).
 */
const CONFIG = {
  PORTAL_API_BASE: 'http://hte-portal-alb-1268363516.ap-southeast-1.elb.amazonaws.com',
  GATEWAY_BASE_URL: 'http://hte-gateway-alb-708965871.ap-southeast-1.elb.amazonaws.com',
};

if (typeof globalThis !== 'undefined') {
  globalThis.KIDS_SAFETY_CONFIG = CONFIG;
}
