"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
# Load .env from backend directory; also try backend/backend/.env as fallback
_env_dir = BASE_DIR.parent
load_dotenv(str(_env_dir / '.env'))
load_dotenv(str(BASE_DIR / '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ngdm43!qlc07jx#00o9jc&vpp*6wv-ar=4+)r2&krxe4m=1+w1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'portal',
]

# CORS for portal API: allow all origins (e.g. frontend on ALB or any domain)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Use PostgreSQL when POSTGRES_DB or POSTGRES_HOST is set (e.g. from .env); otherwise SQLite.

_use_postgres = (
    (os.environ.get('POSTGRES_DB') or '').strip() != ''
    or (os.environ.get('POSTGRES_HOST') or '').strip() != ''
)

if _use_postgres:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': (os.environ.get('POSTGRES_DB') or 'hte').strip(),
            'USER': (os.environ.get('POSTGRES_USER') or 'postgres').strip(),
            'PASSWORD': (os.environ.get('POSTGRES_PASSWORD') or '').strip(),
            'HOST': (os.environ.get('POSTGRES_HOST') or 'localhost').strip(),
            'PORT': (os.environ.get('POSTGRES_PORT') or '5432').strip(),
            'OPTIONS': {'connect_timeout': 5},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF: trust these origins for Referer/Origin check (Django has no wildcard; add via env for more).
# Portal login/logout are also @csrf_exempt so they work from any origin.
_trusted = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://hte-frontend-alb-452710823.ap-southeast-1.elb.amazonaws.com',
    'https://hte-frontend-alb-452710823.ap-southeast-1.elb.amazonaws.com',
]
_extra = (os.environ.get('CSRF_TRUSTED_ORIGINS') or '').strip()
if _extra:
    _trusted.extend(o.strip() for o in _extra.split(',') if o.strip())
CSRF_TRUSTED_ORIGINS = _trusted

# Session/CSRF cookies: use Lax + non-Secure so cookies work over HTTP when frontend uses same-origin proxy
# (do not set NEXT_PUBLIC_API_URL; use DJANGO_API_URL on the Next.js server so browser hits /api/portal/* on frontend)
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax').strip() or 'Lax'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').strip().lower() in ('1', 'true', 'yes')
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax').strip() or 'Lax'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').strip().lower() in ('1', 'true', 'yes')
